[package]
name = "rhusics-ecs"
version = "0.1.1"
authors = ["Simon RÃ¶nnberg <seamonr@gmail.com>"]
repository = "https://github.com/rustgd/rhusics.git"
homepage = "https://github.com/rustgd/rhusics.git"

license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rhusics-ecs"
description = "Physics library for use with `specs`"

keywords = ["gamedev", "cgmath", "specs", "physics"]

[features]
eders = ["serde", "cgmath/serde", "collision/eders", "specs/serde", "rhusics-core/eders"]

[dependencies]
cgmath = "0.16"
collision = { version = "0.14" }
rhusics-core = { version = "0.1.1", path = "../rhusics-core", features = ["specs"] }
specs = "0.10"
shrev = "0.8"
serde = { version = "1.0", optional = true, features = ["derive"]}

[[example]]
name = "basic2d"

[[example]]
name = "basic3d"

[[example]]
name = "spatial3d"

[[example]]
name = "spatial2d"
